/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\object\\vue\\zykBlog\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-2e6b2d69",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2e6b2d69").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-6f4ec764",
    path: "/blogs/oencv/opncv-python.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6f4ec764").then(next)
    },
  },
  {
    name: "v-c4494550",
    path: "/blogs/esp32/mpu6050.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c4494550").then(next)
    },
  },
  {
    name: "v-26ffca18",
    path: "/blogs/pytroch/pytroch.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-26ffca18").then(next)
    },
  },
  {
    name: "v-08560cd0",
    path: "/blogs/web/vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-08560cd0").then(next)
    },
  },
  {
    name: "v-b1564aac",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tags", "v-b1564aac").then(next)
    },
    meta: {"pid":"tags","id":"tags"}
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-ef9325c4",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterKey", "v-ef9325c4").then(next)
    },
    meta: {"pid":"categories","id":"categories"}
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    name: "v-6319eb4e",
    path: "/timeline/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("TimeLines", "v-6319eb4e").then(next)
    },
    meta: {"pid":"timeline","id":"timeline"}
  },
  {
    path: "/timeline/index.html",
    redirect: "/timeline/"
  },
  {
    name: "v-bac21cb0",
    path: "/tag/opencv/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-bac21cb0").then(next)
    },
    meta: {"pid":"tags","id":"opencv"}
  },
  {
    path: "/tag/opencv/index.html",
    redirect: "/tag/opencv/"
  },
  {
    name: "v-309cc62e",
    path: "/tag/python/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-309cc62e").then(next)
    },
    meta: {"pid":"tags","id":"python"}
  },
  {
    path: "/tag/python/index.html",
    redirect: "/tag/python/"
  },
  {
    name: "v-8ae32fd0",
    path: "/tag/esp32/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-8ae32fd0").then(next)
    },
    meta: {"pid":"tags","id":"esp32"}
  },
  {
    path: "/tag/esp32/index.html",
    redirect: "/tag/esp32/"
  },
  {
    name: "v-0f0ec90c",
    path: "/tag/pytroch/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-0f0ec90c").then(next)
    },
    meta: {"pid":"tags","id":"pytroch"}
  },
  {
    path: "/tag/pytroch/index.html",
    redirect: "/tag/pytroch/"
  },
  {
    name: "v-322a45da",
    path: "/tag/vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-322a45da").then(next)
    },
    meta: {"pid":"tags","id":"vue"}
  },
  {
    path: "/tag/vue/index.html",
    redirect: "/tag/vue/"
  },
  {
    name: "v-155fc016",
    path: "/categories/python/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-155fc016").then(next)
    },
    meta: {"pid":"categories","id":"python"}
  },
  {
    path: "/categories/python/index.html",
    redirect: "/categories/python/"
  },
  {
    name: "v-166558e8",
    path: "/categories/esp32/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-166558e8").then(next)
    },
    meta: {"pid":"categories","id":"esp32"}
  },
  {
    path: "/categories/esp32/index.html",
    redirect: "/categories/esp32/"
  },
  {
    name: "v-957eb100",
    path: "/categories/pytroch/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-957eb100").then(next)
    },
    meta: {"pid":"categories","id":"pytroch"}
  },
  {
    path: "/categories/pytroch/index.html",
    redirect: "/categories/pytroch/"
  },
  {
    name: "v-7f164d79",
    path: "/categories/web/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-7f164d79").then(next)
    },
    meta: {"pid":"categories","id":"web"}
  },
  {
    path: "/categories/web/index.html",
    redirect: "/categories/web/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]