/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\Users\\zouyo\\Desktop\\demo\\zykBlog\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-0cb0f154",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0cb0f154").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-68e0875a",
    path: "/blogs/3D%20vision/word.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-68e0875a").then(next)
    },
  },
  {
    path: "/blogs/3D vision/word.html",
    redirect: "/blogs/3D%20vision/word.html"
  },
  {
    path: "/blogs/3D vision/word.html",
    redirect: "/blogs/3D%20vision/word.html"
  },
  {
    name: "v-d2c4ce30",
    path: "/blogs/3D%20vision/conv_and_pool.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d2c4ce30").then(next)
    },
  },
  {
    path: "/blogs/3D vision/conv_and_pool.html",
    redirect: "/blogs/3D%20vision/conv_and_pool.html"
  },
  {
    path: "/blogs/3D vision/conv_and_pool.html",
    redirect: "/blogs/3D%20vision/conv_and_pool.html"
  },
  {
    name: "v-5c7067f0",
    path: "/blogs/Embedded%20Hardware/mpu6050.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5c7067f0").then(next)
    },
  },
  {
    path: "/blogs/Embedded Hardware/mpu6050.html",
    redirect: "/blogs/Embedded%20Hardware/mpu6050.html"
  },
  {
    path: "/blogs/Embedded Hardware/mpu6050.html",
    redirect: "/blogs/Embedded%20Hardware/mpu6050.html"
  },
  {
    name: "v-4685d024",
    path: "/blogs/jetson%20nano/opncv-python.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4685d024").then(next)
    },
  },
  {
    path: "/blogs/jetson nano/opncv-python.html",
    redirect: "/blogs/jetson%20nano/opncv-python.html"
  },
  {
    path: "/blogs/jetson nano/opncv-python.html",
    redirect: "/blogs/jetson%20nano/opncv-python.html"
  },
  {
    name: "v-30564cb6",
    path: "/blogs/Embedded%20Hardware/Embedded_Hardware_Learning_Records.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-30564cb6").then(next)
    },
  },
  {
    path: "/blogs/Embedded Hardware/Embedded_Hardware_Learning_Records.html",
    redirect: "/blogs/Embedded%20Hardware/Embedded_Hardware_Learning_Records.html"
  },
  {
    path: "/blogs/Embedded Hardware/Embedded_Hardware_Learning_Records.html",
    redirect: "/blogs/Embedded%20Hardware/Embedded_Hardware_Learning_Records.html"
  },
  {
    name: "v-7374fd08",
    path: "/blogs/3D%20vision/one.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7374fd08").then(next)
    },
  },
  {
    path: "/blogs/3D vision/one.html",
    redirect: "/blogs/3D%20vision/one.html"
  },
  {
    path: "/blogs/3D vision/one.html",
    redirect: "/blogs/3D%20vision/one.html"
  },
  {
    name: "v-6f983828",
    path: "/blogs/jetson%20nano/qt5Py.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6f983828").then(next)
    },
  },
  {
    path: "/blogs/jetson nano/qt5Py.html",
    redirect: "/blogs/jetson%20nano/qt5Py.html"
  },
  {
    path: "/blogs/jetson nano/qt5Py.html",
    redirect: "/blogs/jetson%20nano/qt5Py.html"
  },
  {
    name: "v-bfc1e6ea",
    path: "/blogs/web/LearnningOS.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bfc1e6ea").then(next)
    },
  },
  {
    name: "v-376dbecb",
    path: "/blogs/pytroch/pytroch.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-376dbecb").then(next)
    },
  },
  {
    name: "v-36f68f2b",
    path: "/blogs/web/node_blog.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-36f68f2b").then(next)
    },
  },
  {
    name: "v-5030b44b",
    path: "/blogs/web/vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5030b44b").then(next)
    },
  },
  {
    name: "v-b1564aac",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tags", "v-b1564aac").then(next)
    },
    meta: {"pid":"tags","id":"tags"}
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-ef9325c4",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterKey", "v-ef9325c4").then(next)
    },
    meta: {"pid":"categories","id":"categories"}
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    name: "v-6319eb4e",
    path: "/timeline/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("TimeLines", "v-6319eb4e").then(next)
    },
    meta: {"pid":"timeline","id":"timeline"}
  },
  {
    path: "/timeline/index.html",
    redirect: "/timeline/"
  },
  {
    name: "v-14055bfa",
    path: "/tag/node/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-14055bfa").then(next)
    },
    meta: {"pid":"tags","id":"node"}
  },
  {
    path: "/tag/node/index.html",
    redirect: "/tag/node/"
  },
  {
    name: "v-7df19544",
    path: "/tag/image/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-7df19544").then(next)
    },
    meta: {"pid":"tags","id":"image"}
  },
  {
    path: "/tag/image/index.html",
    redirect: "/tag/image/"
  },
  {
    name: "v-8ae32fd0",
    path: "/tag/esp32/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-8ae32fd0").then(next)
    },
    meta: {"pid":"tags","id":"esp32"}
  },
  {
    path: "/tag/esp32/index.html",
    redirect: "/tag/esp32/"
  },
  {
    name: "v-bac21cb0",
    path: "/tag/opencv/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-bac21cb0").then(next)
    },
    meta: {"pid":"tags","id":"opencv"}
  },
  {
    path: "/tag/opencv/index.html",
    redirect: "/tag/opencv/"
  },
  {
    name: "v-309cc62e",
    path: "/tag/python/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-309cc62e").then(next)
    },
    meta: {"pid":"tags","id":"python"}
  },
  {
    path: "/tag/python/index.html",
    redirect: "/tag/python/"
  },
  {
    name: "v-192d793b",
    path: "/tag/jetson nano/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-192d793b").then(next)
    },
    meta: {"pid":"tags","id":"jetson nano"}
  },
  {
    path: "/tag/jetson nano/index.html",
    redirect: "/tag/jetson nano/"
  },
  {
    name: "v-0b1c14c6",
    path: "/tag/learnning reword/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-0b1c14c6").then(next)
    },
    meta: {"pid":"tags","id":"learnning reword"}
  },
  {
    path: "/tag/learnning reword/index.html",
    redirect: "/tag/learnning reword/"
  },
  {
    name: "v-2f092b9f",
    path: "/tag/3D vision/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-2f092b9f").then(next)
    },
    meta: {"pid":"tags","id":"3D vision"}
  },
  {
    path: "/tag/3D vision/index.html",
    redirect: "/tag/3D vision/"
  },
  {
    name: "v-e8d838fc",
    path: "/tag/qt/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-e8d838fc").then(next)
    },
    meta: {"pid":"tags","id":"qt"}
  },
  {
    path: "/tag/qt/index.html",
    redirect: "/tag/qt/"
  },
  {
    name: "v-dd73a992",
    path: "/tag/ubuntu18/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-dd73a992").then(next)
    },
    meta: {"pid":"tags","id":"ubuntu18"}
  },
  {
    path: "/tag/ubuntu18/index.html",
    redirect: "/tag/ubuntu18/"
  },
  {
    name: "v-0f0ec90c",
    path: "/tag/pytroch/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-0f0ec90c").then(next)
    },
    meta: {"pid":"tags","id":"pytroch"}
  },
  {
    path: "/tag/pytroch/index.html",
    redirect: "/tag/pytroch/"
  },
  {
    name: "v-dfb71430",
    path: "/tag/vuepress/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-dfb71430").then(next)
    },
    meta: {"pid":"tags","id":"vuepress"}
  },
  {
    path: "/tag/vuepress/index.html",
    redirect: "/tag/vuepress/"
  },
  {
    name: "v-322a45da",
    path: "/tag/vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-322a45da").then(next)
    },
    meta: {"pid":"tags","id":"vue"}
  },
  {
    path: "/tag/vue/index.html",
    redirect: "/tag/vue/"
  },
  {
    name: "v-d9029fda",
    path: "/categories/3D vision/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-d9029fda").then(next)
    },
    meta: {"pid":"categories","id":"3D vision"}
  },
  {
    path: "/categories/3D vision/index.html",
    redirect: "/categories/3D vision/"
  },
  {
    name: "v-68b501a8",
    path: "/categories/Embedded Hardware/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-68b501a8").then(next)
    },
    meta: {"pid":"categories","id":"Embedded Hardware"}
  },
  {
    path: "/categories/Embedded Hardware/index.html",
    redirect: "/categories/Embedded Hardware/"
  },
  {
    name: "v-3653b0af",
    path: "/categories/jetson nano/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-3653b0af").then(next)
    },
    meta: {"pid":"categories","id":"jetson nano"}
  },
  {
    path: "/categories/jetson nano/index.html",
    redirect: "/categories/jetson nano/"
  },
  {
    name: "v-7f164d79",
    path: "/categories/web/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-7f164d79").then(next)
    },
    meta: {"pid":"categories","id":"web"}
  },
  {
    path: "/categories/web/index.html",
    redirect: "/categories/web/"
  },
  {
    name: "v-957eb100",
    path: "/categories/pytroch/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-957eb100").then(next)
    },
    meta: {"pid":"categories","id":"pytroch"}
  },
  {
    path: "/categories/pytroch/index.html",
    redirect: "/categories/pytroch/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]