/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "zyk space",
  "description": "",
  "base": "/zykBlog/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/zykBlog/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "viewport",
        "content": "width=device-width,initial-scale=1,user-scalable=no"
      }
    ]
  ],
  "pages": [
    {
      "title": "深度学习记录",
      "frontmatter": {
        "title": "深度学习记录",
        "date": "2023/3/22",
        "tags": [
          "DL"
        ],
        "categories": "3D vision"
      },
      "regularPath": "/blogs/3D%20vision/DL.html",
      "relativePath": "blogs/3D vision/DL.md",
      "key": "v-33a69e2a",
      "path": "/blogs/3D%20vision/DL.html",
      "headers": [
        {
          "level": 2,
          "title": "过程",
          "slug": "过程"
        },
        {
          "level": 3,
          "title": "经典的激活函数",
          "slug": "经典的激活函数"
        },
        {
          "level": 3,
          "title": "relu激活函数（斜坡函数）",
          "slug": "relu激活函数-斜坡函数"
        },
        {
          "level": 3,
          "title": "tanh激活函数（双曲正切）",
          "slug": "tanh激活函数-双曲正切"
        },
        {
          "level": 2,
          "title": "神经网络与经典的网络架构",
          "slug": "神经网络与经典的网络架构"
        },
        {
          "level": 3,
          "title": "全连接神经网络",
          "slug": "全连接神经网络"
        },
        {
          "level": 3,
          "title": "卷积神经网络",
          "slug": "卷积神经网络"
        },
        {
          "level": 3,
          "title": "rcnn",
          "slug": "rcnn"
        },
        {
          "level": 3,
          "title": "fast-rcnn 、faster-rcnn & marks-rcnn",
          "slug": "fast-rcnn-、faster-rcnn-marks-rcnn"
        },
        {
          "level": 3,
          "title": "transformer",
          "slug": "transformer"
        },
        {
          "level": 2,
          "title": "",
          "slug": ""
        }
      ],
      "lastUpdated": "3/28/2023, 8:46:58 PM",
      "lastUpdatedTimestamp": 1680007618000
    },
    {
      "title": "机器学习笔记",
      "frontmatter": {
        "title": "机器学习笔记",
        "date": "2023/3/22",
        "tags": [
          "python",
          "ML",
          "CNN"
        ],
        "categories": "3D vision"
      },
      "regularPath": "/blogs/3D%20vision/ML.html",
      "relativePath": "blogs/3D vision/ML.md",
      "key": "v-7e73d07d",
      "path": "/blogs/3D%20vision/ML.html",
      "headers": [
        {
          "level": 2,
          "title": "Tensorflow安装",
          "slug": "tensorflow安装"
        },
        {
          "level": 2,
          "title": "Kaggle比赛",
          "slug": "kaggle比赛"
        },
        {
          "level": 2,
          "title": "ML学习",
          "slug": "ml学习"
        },
        {
          "level": 3,
          "title": "线性回归",
          "slug": "线性回归"
        },
        {
          "level": 3,
          "title": "逻辑回归",
          "slug": "逻辑回归"
        },
        {
          "level": 3,
          "title": "支持向量机（SVM）",
          "slug": "支持向量机-svm"
        },
        {
          "level": 3,
          "title": "朴素贝叶斯",
          "slug": "朴素贝叶斯"
        },
        {
          "level": 3,
          "title": "决策树",
          "slug": "决策树"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "word ＆ node",
        "tagline": "一个存放个人笔记的地方。",
        "bgImageStyle": {
          "height": "750px"
        },
        "isShowTitleInHome": false
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-2e6b2d69",
      "path": "/",
      "lastUpdated": "3/22/2023, 8:34:00 PM",
      "lastUpdatedTimestamp": 1679488440000
    },
    {
      "title": "3D 相关的词解",
      "frontmatter": {
        "title": "3D 相关的词解",
        "tags": [
          "node"
        ],
        "categories": "3D vision"
      },
      "regularPath": "/blogs/3D%20vision/word.html",
      "relativePath": "blogs/3D vision/word.md",
      "key": "v-587292a7",
      "path": "/blogs/3D%20vision/word.html",
      "headers": [
        {
          "level": 2,
          "title": "图像",
          "slug": "图像"
        },
        {
          "level": 2,
          "title": "网络",
          "slug": "网络"
        },
        {
          "level": 2,
          "title": "yolo & 3d",
          "slug": "yolo-3d"
        },
        {
          "level": 3,
          "title": "Complex yolov4",
          "slug": "complex-yolov4"
        },
        {
          "level": 3,
          "title": "YOLO-6D",
          "slug": "yolo-6d"
        }
      ],
      "lastUpdated": "3/22/2023, 8:34:00 PM",
      "lastUpdatedTimestamp": 1679488440000
    },
    {
      "title": "3D视觉基础知识",
      "frontmatter": {
        "title": "3D视觉基础知识",
        "tags": [
          "3D vision"
        ],
        "categories": "3D vision"
      },
      "regularPath": "/blogs/3D%20vision/node.html",
      "relativePath": "blogs/3D vision/node.md",
      "key": "v-47ed80b7",
      "path": "/blogs/3D%20vision/node.html",
      "headers": [
        {
          "level": 3,
          "title": "三维空间的描述",
          "slug": "三维空间的描述"
        }
      ],
      "lastUpdated": "3/28/2023, 8:46:58 PM",
      "lastUpdatedTimestamp": 1680007618000
    },
    {
      "title": "卷积和池化",
      "frontmatter": {
        "title": "卷积和池化",
        "date": "2023/3/10",
        "tags": [
          "cnn"
        ],
        "categories": "3D vision"
      },
      "regularPath": "/blogs/3D%20vision/conv_and_pool.html",
      "relativePath": "blogs/3D vision/conv_and_pool.md",
      "key": "v-97bb6a16",
      "path": "/blogs/3D%20vision/conv_and_pool.html",
      "headers": [
        {
          "level": 2,
          "title": "池化",
          "slug": "池化"
        }
      ],
      "lastUpdated": "3/28/2023, 8:46:58 PM",
      "lastUpdatedTimestamp": 1680007618000
    },
    {
      "title": "Esp32",
      "frontmatter": {
        "title": "Esp32",
        "date": "2023/03/31 22:54:44",
        "author": "zyk",
        "tags": [
          null
        ],
        "categories": "Embedded Hardware"
      },
      "regularPath": "/blogs/Embedded%20Hardware/Esp32.html",
      "relativePath": "blogs/Embedded Hardware/Esp32.md",
      "key": "v-6f309815",
      "path": "/blogs/Embedded%20Hardware/Esp32.html",
      "headers": [
        {
          "level": 2,
          "title": "陀螺仪",
          "slug": "陀螺仪"
        },
        {
          "level": 2,
          "title": "MPU6050模块",
          "slug": "mpu6050模块"
        }
      ]
    },
    {
      "title": "Stm32笔记",
      "frontmatter": {
        "title": "Stm32笔记",
        "date": "2023/3/31",
        "tags": [
          "Stm32"
        ],
        "categories": "Embedded Hardware"
      },
      "regularPath": "/blogs/Embedded%20Hardware/Stm32.html",
      "relativePath": "blogs/Embedded Hardware/Stm32.md",
      "key": "v-a06f1f56",
      "path": "/blogs/Embedded%20Hardware/Stm32.html",
      "headers": [
        {
          "level": 2,
          "title": "STM 32",
          "slug": "stm-32"
        },
        {
          "level": 3,
          "title": "小常识",
          "slug": "小常识"
        },
        {
          "level": 2,
          "title": "标准库",
          "slug": "标准库"
        },
        {
          "level": 3,
          "title": "如何构建项目",
          "slug": "如何构建项目"
        },
        {
          "level": 2,
          "title": "HAL库",
          "slug": "hal库"
        },
        {
          "level": 3,
          "title": "GPIO和按键",
          "slug": "gpio和按键"
        },
        {
          "level": 3,
          "title": "定时器",
          "slug": "定时器"
        },
        {
          "level": 3,
          "title": "OLED",
          "slug": "oled"
        },
        {
          "level": 3,
          "title": "串口和定时器串口",
          "slug": "串口和定时器串口"
        }
      ]
    },
    {
      "title": "51单片机学习记录",
      "frontmatter": {
        "title": "51单片机学习记录",
        "date": "2022/8/1",
        "tags": [
          "learnning reword"
        ],
        "categories": "Embedded Hardware"
      },
      "regularPath": "/blogs/Embedded%20Hardware/51MCU.html",
      "relativePath": "blogs/Embedded Hardware/51MCU.md",
      "key": "v-96de5956",
      "path": "/blogs/Embedded%20Hardware/51MCU.html",
      "headers": [
        {
          "level": 3,
          "title": "缺少的库",
          "slug": "缺少的库"
        },
        {
          "level": 3,
          "title": "软件学习记录",
          "slug": "软件学习记录"
        },
        {
          "level": 3,
          "title": "使用技巧",
          "slug": "使用技巧"
        },
        {
          "level": 2,
          "title": "寻址方式",
          "slug": "寻址方式"
        },
        {
          "level": 3,
          "title": "小知识点",
          "slug": "小知识点"
        },
        {
          "level": 2,
          "title": "指令系统",
          "slug": "指令系统"
        },
        {
          "level": 3,
          "title": "小知识点",
          "slug": "小知识点-2"
        },
        {
          "level": 2,
          "title": "基本的程序结构",
          "slug": "基本的程序结构"
        },
        {
          "level": 3,
          "title": "定时/计数器",
          "slug": "定时-计数器"
        },
        {
          "level": 3,
          "title": "中断",
          "slug": "中断"
        },
        {
          "level": 3,
          "title": "网络通信的知识",
          "slug": "网络通信的知识"
        },
        {
          "level": 3,
          "title": "串口通信",
          "slug": "串口通信"
        },
        {
          "level": 3,
          "title": "IIC协议",
          "slug": "iic协议"
        },
        {
          "level": 3,
          "title": "SPI协议",
          "slug": "spi协议"
        }
      ]
    },
    {
      "title": "Opencv使用踩坑记录",
      "frontmatter": {
        "title": "Opencv使用踩坑记录",
        "date": "2023/3/18",
        "tags": [
          "opencv",
          "python",
          "jetson nano"
        ],
        "categories": "jetson nano"
      },
      "regularPath": "/blogs/Embedded%20Hardware/opncv-python.html",
      "relativePath": "blogs/Embedded Hardware/opncv-python.md",
      "key": "v-32633d92",
      "path": "/blogs/Embedded%20Hardware/opncv-python.html",
      "headers": [
        {
          "level": 3,
          "title": "摄像头驱动",
          "slug": "摄像头驱动"
        }
      ]
    },
    {
      "title": "jetson nano 的ubuntu使用记录",
      "frontmatter": {
        "title": "jetson nano 的ubuntu使用记录",
        "date": "2023/3/28",
        "tags": [
          "qt",
          "ubuntu18",
          "jetson nano"
        ],
        "categories": "Embedded Hardware"
      },
      "regularPath": "/blogs/Embedded%20Hardware/jetson-nano.html",
      "relativePath": "blogs/Embedded Hardware/jetson-nano.md",
      "key": "v-362f0416",
      "path": "/blogs/Embedded%20Hardware/jetson-nano.html",
      "headers": [
        {
          "level": 2,
          "title": "pycharm 安装（注意 是arm 64）",
          "slug": "pycharm-安装-注意-是arm-64"
        },
        {
          "level": 2,
          "title": "py-qt5",
          "slug": "py-qt5"
        },
        {
          "level": 2,
          "title": "minconda",
          "slug": "minconda"
        }
      ]
    },
    {
      "title": "python 笔记",
      "frontmatter": {
        "title": "python 笔记",
        "date": "2023/3/22",
        "tags": [
          "python"
        ],
        "categories": "python"
      },
      "regularPath": "/blogs/python/node.html",
      "relativePath": "blogs/python/node.md",
      "key": "v-37896e5c",
      "path": "/blogs/python/node.html",
      "headers": [
        {
          "level": 2,
          "title": "小技巧和注意点",
          "slug": "小技巧和注意点"
        },
        {
          "level": 2,
          "title": "基础语法",
          "slug": "基础语法"
        },
        {
          "level": 3,
          "title": "标识符",
          "slug": "标识符"
        },
        {
          "level": 3,
          "title": "多行语法",
          "slug": "多行语法"
        },
        {
          "level": 3,
          "title": "字符串的使用",
          "slug": "字符串的使用"
        },
        {
          "level": 3,
          "title": "导包",
          "slug": "导包"
        },
        {
          "level": 2,
          "title": "数据类型",
          "slug": "数据类型"
        },
        {
          "level": 3,
          "title": "Number（数字）",
          "slug": "number-数字"
        },
        {
          "level": 3,
          "title": "String（字符串）",
          "slug": "string-字符串"
        },
        {
          "level": 3,
          "title": "Tuple（元组）",
          "slug": "tuple-元组"
        },
        {
          "level": 3,
          "title": "List（列表）",
          "slug": "list-列表"
        },
        {
          "level": 3,
          "title": "Set（集合）",
          "slug": "set-集合"
        },
        {
          "level": 3,
          "title": "Dictionary（字典）",
          "slug": "dictionary-字典"
        },
        {
          "level": 3,
          "title": "常见的数据类型转换函数",
          "slug": "常见的数据类型转换函数"
        },
        {
          "level": 2,
          "title": "推导式",
          "slug": "推导式"
        },
        {
          "level": 2,
          "title": "运算符号",
          "slug": "运算符号"
        },
        {
          "level": 2,
          "title": "解释器",
          "slug": "解释器"
        },
        {
          "level": 2,
          "title": "迭代器与生成器",
          "slug": "迭代器与生成器"
        },
        {
          "level": 2,
          "title": "面向对象和类",
          "slug": "面向对象和类"
        },
        {
          "level": 2,
          "title": "装饰器",
          "slug": "装饰器"
        },
        {
          "level": 2,
          "title": "并发编程",
          "slug": "并发编程"
        },
        {
          "level": 3,
          "title": "",
          "slug": ""
        },
        {
          "level": 2,
          "title": "算法",
          "slug": "算法"
        },
        {
          "level": 3,
          "title": "数组去重",
          "slug": "数组去重"
        }
      ]
    },
    {
      "title": "初识pytroch",
      "frontmatter": {
        "title": "初识pytroch",
        "date": "2023/3/22",
        "tags": [
          "python",
          "pytroch"
        ],
        "categories": "python"
      },
      "regularPath": "/blogs/python/pytroch.html",
      "relativePath": "blogs/python/pytroch.md",
      "key": "v-5d52d5ae",
      "path": "/blogs/python/pytroch.html",
      "headers": [
        {
          "level": 2,
          "title": "环境配置",
          "slug": "环境配置"
        },
        {
          "level": 2,
          "title": "相关知识点",
          "slug": "相关知识点"
        },
        {
          "level": 2,
          "title": "pytorch的基本使用",
          "slug": "pytorch的基本使用"
        }
      ],
      "lastUpdated": "3/22/2023, 8:34:00 PM",
      "lastUpdatedTimestamp": 1679488440000
    },
    {
      "title": "k-means",
      "frontmatter": {
        "title": "k-means",
        "date": "2023/3/23",
        "tags": [
          "聚类"
        ],
        "categories": "papers"
      },
      "regularPath": "/blogs/papers/k-means.html",
      "relativePath": "blogs/papers/k-means.md",
      "key": "v-e14db1cc",
      "path": "/blogs/papers/k-means.html",
      "lastUpdated": "3/28/2023, 8:46:58 PM",
      "lastUpdatedTimestamp": 1680007618000
    },
    {
      "title": "c++ 学习记录",
      "frontmatter": {
        "title": "c++ 学习记录",
        "date": "2022/10/10",
        "tags": [
          "c++"
        ],
        "categories": "c++"
      },
      "regularPath": "/blogs/c++/node.html",
      "relativePath": "blogs/c++/node.md",
      "key": "v-324f94e8",
      "path": "/blogs/c++/node.html",
      "headers": [
        {
          "level": 2,
          "title": "C++语法",
          "slug": "c-语法"
        },
        {
          "level": 3,
          "title": "小细节",
          "slug": "小细节"
        },
        {
          "level": 3,
          "title": "常识",
          "slug": "常识"
        },
        {
          "level": 2,
          "title": "内容",
          "slug": "内容"
        },
        {
          "level": 3,
          "title": "文件和流",
          "slug": "文件和流"
        },
        {
          "level": 3,
          "title": "异常处理",
          "slug": "异常处理"
        },
        {
          "level": 3,
          "title": "动态内存",
          "slug": "动态内存"
        },
        {
          "level": 3,
          "title": "命名空间",
          "slug": "命名空间"
        },
        {
          "level": 3,
          "title": "模板",
          "slug": "模板"
        },
        {
          "level": 3,
          "title": "多线程",
          "slug": "多线程"
        },
        {
          "level": 3,
          "title": "STL",
          "slug": "stl"
        }
      ],
      "lastUpdated": "3/28/2023, 8:46:58 PM",
      "lastUpdatedTimestamp": 1680007618000
    },
    {
      "title": "计算机网络笔记",
      "frontmatter": {
        "title": "计算机网络笔记",
        "tags": [
          "net work"
        ],
        "categories": "web"
      },
      "regularPath": "/blogs/web/LernningNetWork.html",
      "relativePath": "blogs/web/LernningNetWork.md",
      "key": "v-518e1fb8",
      "path": "/blogs/web/LernningNetWork.html",
      "headers": [
        {
          "level": 2,
          "title": "模型",
          "slug": "模型"
        }
      ],
      "lastUpdated": "3/22/2023, 8:34:00 PM",
      "lastUpdatedTimestamp": 1679488440000
    },
    {
      "title": "计算机操作系统学习记录",
      "frontmatter": {
        "title": "计算机操作系统学习记录",
        "date": "2023/3/22",
        "tags": [
          "learnning reword"
        ],
        "categories": "web"
      },
      "regularPath": "/blogs/web/LearnningOS.html",
      "relativePath": "blogs/web/LearnningOS.md",
      "key": "v-e09dd050",
      "path": "/blogs/web/LearnningOS.html",
      "headers": [
        {
          "level": 3,
          "title": "概述",
          "slug": "概述"
        },
        {
          "level": 3,
          "title": "发展过程",
          "slug": "发展过程"
        },
        {
          "level": 3,
          "title": "内核",
          "slug": "内核"
        },
        {
          "level": 2,
          "title": "进程于线程",
          "slug": "进程于线程"
        },
        {
          "level": 3,
          "title": "进程",
          "slug": "进程"
        },
        {
          "level": 3,
          "title": "进程的状态转换",
          "slug": "进程的状态转换"
        },
        {
          "level": 3,
          "title": "进程通信",
          "slug": "进程通信"
        },
        {
          "level": 3,
          "title": "线程",
          "slug": "线程"
        },
        {
          "level": 2,
          "title": "调度",
          "slug": "调度"
        },
        {
          "level": 3,
          "title": "处理机调度",
          "slug": "处理机调度"
        },
        {
          "level": 3,
          "title": "调度算法的评估指标",
          "slug": "调度算法的评估指标"
        },
        {
          "level": 3,
          "title": "调度算法",
          "slug": "调度算法"
        },
        {
          "level": 2,
          "title": "同步和互斥",
          "slug": "同步和互斥"
        },
        {
          "level": 3,
          "title": "同步",
          "slug": "同步"
        },
        {
          "level": 3,
          "title": "互斥",
          "slug": "互斥"
        },
        {
          "level": 3,
          "title": "信号量机制",
          "slug": "信号量机制"
        }
      ],
      "lastUpdated": "3/22/2023, 8:34:00 PM",
      "lastUpdatedTimestamp": 1679488440000
    },
    {
      "title": "vuepress搭建blog记录",
      "frontmatter": {
        "title": "vuepress搭建blog记录",
        "date": "2023/3/22",
        "tags": [
          "vuepress",
          "vue"
        ],
        "categories": "web"
      },
      "regularPath": "/blogs/web/node_blog.html",
      "relativePath": "blogs/web/node_blog.md",
      "key": "v-ca776e10",
      "path": "/blogs/web/node_blog.html",
      "headers": [
        {
          "level": 3,
          "title": "学习记录",
          "slug": "学习记录"
        },
        {
          "level": 2,
          "title": "1、md文件模板",
          "slug": "_1、md文件模板"
        },
        {
          "level": 3,
          "title": "部署记录",
          "slug": "部署记录"
        },
        {
          "level": 3,
          "title": "模板",
          "slug": "模板"
        },
        {
          "level": 3,
          "title": "公式插件",
          "slug": "公式插件"
        },
        {
          "level": 3,
          "title": "vscode配置代码段自动生成bloghead",
          "slug": "vscode配置代码段自动生成bloghead"
        },
        {
          "level": 3,
          "title": "目录分级管理",
          "slug": "目录分级管理"
        }
      ],
      "lastUpdated": "3/28/2023, 8:46:58 PM",
      "lastUpdatedTimestamp": 1680007618000
    },
    {
      "title": "Vue",
      "frontmatter": {
        "title": "Vue",
        "date": "2023/3/22",
        "tags": [
          "vue"
        ],
        "categories": "web"
      },
      "regularPath": "/blogs/web/vue.html",
      "relativePath": "blogs/web/vue.md",
      "key": "v-08560cd0",
      "path": "/blogs/web/vue.html",
      "headers": [
        {
          "level": 2,
          "title": "VUE2",
          "slug": "vue2"
        },
        {
          "level": 3,
          "title": "模板语法template",
          "slug": "模板语法template"
        },
        {
          "level": 3,
          "title": "数据代理",
          "slug": "数据代理"
        },
        {
          "level": 3,
          "title": "事件",
          "slug": "事件"
        },
        {
          "level": 2,
          "title": "VUE3",
          "slug": "vue3"
        },
        {
          "level": 2,
          "title": "blog",
          "slug": "blog"
        },
        {
          "level": 3,
          "title": "华为为AGC的兼容性插件解决方法",
          "slug": "华为为agc的兼容性插件解决方法"
        },
        {
          "level": 3,
          "title": "使用多表，同数据域",
          "slug": "使用多表-同数据域"
        },
        {
          "level": 3,
          "title": "css记录",
          "slug": "css记录"
        },
        {
          "level": 3,
          "title": "动态图表",
          "slug": "动态图表"
        },
        {
          "level": 2,
          "title": "tensorflow.js",
          "slug": "tensorflow-js"
        },
        {
          "level": 3,
          "title": "基本使用",
          "slug": "基本使用"
        },
        {
          "level": 3,
          "title": "回归曲线",
          "slug": "回归曲线"
        }
      ],
      "lastUpdated": "3/22/2023, 8:34:00 PM",
      "lastUpdatedTimestamp": 1679488440000
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "DL Tags"
      },
      "regularPath": "/tag/DL/",
      "key": "v-e8d99486",
      "path": "/tag/DL/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "python Tags"
      },
      "regularPath": "/tag/python/",
      "key": "v-309cc62e",
      "path": "/tag/python/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "ML Tags"
      },
      "regularPath": "/tag/ML/",
      "key": "v-e8d950f4",
      "path": "/tag/ML/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "CNN Tags"
      },
      "regularPath": "/tag/CNN/",
      "key": "v-3259ce14",
      "path": "/tag/CNN/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "node Tags"
      },
      "regularPath": "/tag/node/",
      "key": "v-14055bfa",
      "path": "/tag/node/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "3D vision Tags"
      },
      "regularPath": "/tag/3D%20vision/",
      "key": "v-2f092b9f",
      "path": "/tag/3D vision/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "cnn Tags"
      },
      "regularPath": "/tag/cnn/",
      "key": "v-323bbe54",
      "path": "/tag/cnn/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "Stm32 Tags"
      },
      "regularPath": "/tag/Stm32/",
      "key": "v-c8383164",
      "path": "/tag/Stm32/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "learnning reword Tags"
      },
      "regularPath": "/tag/learnning%20reword/",
      "key": "v-0b1c14c6",
      "path": "/tag/learnning reword/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "opencv Tags"
      },
      "regularPath": "/tag/opencv/",
      "key": "v-bac21cb0",
      "path": "/tag/opencv/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "jetson nano Tags"
      },
      "regularPath": "/tag/jetson%20nano/",
      "key": "v-192d793b",
      "path": "/tag/jetson nano/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "qt Tags"
      },
      "regularPath": "/tag/qt/",
      "key": "v-e8d838fc",
      "path": "/tag/qt/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "ubuntu18 Tags"
      },
      "regularPath": "/tag/ubuntu18/",
      "key": "v-dd73a992",
      "path": "/tag/ubuntu18/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "pytroch Tags"
      },
      "regularPath": "/tag/pytroch/",
      "key": "v-0f0ec90c",
      "path": "/tag/pytroch/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "聚类 Tags"
      },
      "regularPath": "/tag/%E8%81%9A%E7%B1%BB/",
      "key": "v-767d94a4",
      "path": "/tag/聚类/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "c++ Tags"
      },
      "regularPath": "/tag/c++/",
      "key": "v-323dc594",
      "path": "/tag/c++/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "net work Tags"
      },
      "regularPath": "/tag/net%20work/",
      "key": "v-4b3788a4",
      "path": "/tag/net work/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "vuepress Tags"
      },
      "regularPath": "/tag/vuepress/",
      "key": "v-dfb71430",
      "path": "/tag/vuepress/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "vue Tags"
      },
      "regularPath": "/tag/vue/",
      "key": "v-322a45da",
      "path": "/tag/vue/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "3D vision Categories"
      },
      "regularPath": "/categories/3D%20vision/",
      "key": "v-d9029fda",
      "path": "/categories/3D vision/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "Embedded Hardware Categories"
      },
      "regularPath": "/categories/Embedded%20Hardware/",
      "key": "v-68b501a8",
      "path": "/categories/Embedded Hardware/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "jetson nano Categories"
      },
      "regularPath": "/categories/jetson%20nano/",
      "key": "v-3653b0af",
      "path": "/categories/jetson nano/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "python Categories"
      },
      "regularPath": "/categories/python/",
      "key": "v-155fc016",
      "path": "/categories/python/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "papers Categories"
      },
      "regularPath": "/categories/papers/",
      "key": "v-67bbbc6c",
      "path": "/categories/papers/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "c++ Categories"
      },
      "regularPath": "/categories/c++/",
      "key": "v-7f0c55aa",
      "path": "/categories/c++/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "web Categories"
      },
      "regularPath": "/categories/web/",
      "key": "v-7f164d79",
      "path": "/categories/web/"
    }
  ],
  "themeConfig": {
    "mode": "light",
    "modePicker": false,
    "nav": [
      {
        "text": "主页",
        "link": "/",
        "icon": "reco-home"
      },
      {
        "text": "时间线",
        "link": "/timeline/",
        "icon": "reco-date"
      },
      {
        "text": "关于",
        "icon": "reco-message",
        "items": [
          {
            "text": "GitHub",
            "link": "https://github.com/recoluan",
            "icon": "reco-github"
          }
        ]
      }
    ],
    "sidebar": "auto",
    "type": "blog",
    "blogConfig": {
      "category": {
        "location": 2,
        "text": "分类"
      },
      "tag": {
        "location": 3,
        "text": "标签"
      }
    },
    "logo": "/logo.png",
    "search": false,
    "searchMaxSuggestions": 10,
    "lastUpdated": "上次更新时间",
    "author": "zyk",
    "authorAvatar": "/user.png",
    "startYear": "2023"
  }
}