/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "node": {
      "key": "node",
      "scope": "tags",
      "path": "/tag/node/",
      "pageKeys": [
        "v-68e0875a"
      ]
    },
    "image": {
      "key": "image",
      "scope": "tags",
      "path": "/tag/image/",
      "pageKeys": [
        "v-d2c4ce30"
      ]
    },
    "esp32": {
      "key": "esp32",
      "scope": "tags",
      "path": "/tag/esp32/",
      "pageKeys": [
        "v-5c7067f0"
      ]
    },
    "opencv": {
      "key": "opencv",
      "scope": "tags",
      "path": "/tag/opencv/",
      "pageKeys": [
        "v-4685d024"
      ]
    },
    "python": {
      "key": "python",
      "scope": "tags",
      "path": "/tag/python/",
      "pageKeys": [
        "v-4685d024"
      ]
    },
    "jetson nano": {
      "key": "jetson nano",
      "scope": "tags",
      "path": "/tag/jetson nano/",
      "pageKeys": [
        "v-4685d024",
        "v-6f983828"
      ]
    },
    "learnning reword": {
      "key": "learnning reword",
      "scope": "tags",
      "path": "/tag/learnning reword/",
      "pageKeys": [
        "v-30564cb6",
        "v-bfc1e6ea"
      ]
    },
    "3D vision": {
      "key": "3D vision",
      "scope": "tags",
      "path": "/tag/3D vision/",
      "pageKeys": [
        "v-7374fd08"
      ]
    },
    "qt": {
      "key": "qt",
      "scope": "tags",
      "path": "/tag/qt/",
      "pageKeys": [
        "v-6f983828"
      ]
    },
    "ubuntu18": {
      "key": "ubuntu18",
      "scope": "tags",
      "path": "/tag/ubuntu18/",
      "pageKeys": [
        "v-6f983828"
      ]
    },
    "pytroch": {
      "key": "pytroch",
      "scope": "tags",
      "path": "/tag/pytroch/",
      "pageKeys": [
        "v-376dbecb"
      ]
    },
    "vuepress": {
      "key": "vuepress",
      "scope": "tags",
      "path": "/tag/vuepress/",
      "pageKeys": [
        "v-36f68f2b"
      ]
    },
    "vue": {
      "key": "vue",
      "scope": "tags",
      "path": "/tag/vue/",
      "pageKeys": [
        "v-36f68f2b",
        "v-5030b44b"
      ]
    }
  },
  "categories": {
    "3D vision": {
      "key": "3D vision",
      "scope": "categories",
      "path": "/categories/3D vision/",
      "pageKeys": [
        "v-68e0875a",
        "v-d2c4ce30",
        "v-7374fd08"
      ]
    },
    "Embedded Hardware": {
      "key": "Embedded Hardware",
      "scope": "categories",
      "path": "/categories/Embedded Hardware/",
      "pageKeys": [
        "v-5c7067f0",
        "v-30564cb6"
      ]
    },
    "jetson nano": {
      "key": "jetson nano",
      "scope": "categories",
      "path": "/categories/jetson nano/",
      "pageKeys": [
        "v-4685d024",
        "v-6f983828"
      ]
    },
    "web": {
      "key": "web",
      "scope": "categories",
      "path": "/categories/web/",
      "pageKeys": [
        "v-bfc1e6ea",
        "v-36f68f2b",
        "v-5030b44b"
      ]
    },
    "pytroch": {
      "key": "pytroch",
      "scope": "categories",
      "path": "/categories/pytroch/",
      "pageKeys": [
        "v-376dbecb"
      ]
    }
  },
  "timeline": {}
}