/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "image": {
      "key": "image",
      "scope": "tags",
      "path": "/tag/image/",
      "pageKeys": [
        "v-97bb6a16"
      ]
    },
    "3D vision": {
      "key": "3D vision",
      "scope": "tags",
      "path": "/tag/3D vision/",
      "pageKeys": [
        "v-1abb7795"
      ]
    },
    "esp32": {
      "key": "esp32",
      "scope": "tags",
      "path": "/tag/esp32/",
      "pageKeys": [
        "v-5a5aaf95"
      ]
    },
    "node": {
      "key": "node",
      "scope": "tags",
      "path": "/tag/node/",
      "pageKeys": [
        "v-587292a7"
      ]
    },
    "learnning reword": {
      "key": "learnning reword",
      "scope": "tags",
      "path": "/tag/learnning reword/",
      "pageKeys": [
        "v-3b1836fa",
        "v-e09dd050"
      ]
    },
    "c++": {
      "key": "c++",
      "scope": "tags",
      "path": "/tag/c++/",
      "pageKeys": [
        "v-324f94e8"
      ]
    },
    "qt": {
      "key": "qt",
      "scope": "tags",
      "path": "/tag/qt/",
      "pageKeys": [
        "v-91145496"
      ]
    },
    "ubuntu18": {
      "key": "ubuntu18",
      "scope": "tags",
      "path": "/tag/ubuntu18/",
      "pageKeys": [
        "v-91145496"
      ]
    },
    "jetson nano": {
      "key": "jetson nano",
      "scope": "tags",
      "path": "/tag/jetson nano/",
      "pageKeys": [
        "v-91145496",
        "v-15a632f1"
      ]
    },
    "opencv": {
      "key": "opencv",
      "scope": "tags",
      "path": "/tag/opencv/",
      "pageKeys": [
        "v-15a632f1"
      ]
    },
    "python": {
      "key": "python",
      "scope": "tags",
      "path": "/tag/python/",
      "pageKeys": [
        "v-15a632f1",
        "v-0620935c",
        "v-43ee007e",
        "v-5d52d5ae"
      ]
    },
    "DL": {
      "key": "DL",
      "scope": "tags",
      "path": "/tag/DL/",
      "pageKeys": [
        "v-0620935c"
      ]
    },
    "CNN": {
      "key": "CNN",
      "scope": "tags",
      "path": "/tag/CNN/",
      "pageKeys": [
        "v-0620935c"
      ]
    },
    "pytroch": {
      "key": "pytroch",
      "scope": "tags",
      "path": "/tag/pytroch/",
      "pageKeys": [
        "v-5d52d5ae"
      ]
    },
    "net work": {
      "key": "net work",
      "scope": "tags",
      "path": "/tag/net work/",
      "pageKeys": [
        "v-518e1fb8"
      ]
    },
    "vuepress": {
      "key": "vuepress",
      "scope": "tags",
      "path": "/tag/vuepress/",
      "pageKeys": [
        "v-ca776e10"
      ]
    },
    "vue": {
      "key": "vue",
      "scope": "tags",
      "path": "/tag/vue/",
      "pageKeys": [
        "v-ca776e10",
        "v-08560cd0"
      ]
    }
  },
  "categories": {
    "3D vision": {
      "key": "3D vision",
      "scope": "categories",
      "path": "/categories/3D vision/",
      "pageKeys": [
        "v-97bb6a16",
        "v-1abb7795",
        "v-587292a7"
      ]
    },
    "Embedded Hardware": {
      "key": "Embedded Hardware",
      "scope": "categories",
      "path": "/categories/Embedded Hardware/",
      "pageKeys": [
        "v-5a5aaf95",
        "v-3b1836fa"
      ]
    },
    "c++": {
      "key": "c++",
      "scope": "categories",
      "path": "/categories/c++/",
      "pageKeys": [
        "v-324f94e8"
      ]
    },
    "jetson nano": {
      "key": "jetson nano",
      "scope": "categories",
      "path": "/categories/jetson nano/",
      "pageKeys": [
        "v-91145496",
        "v-15a632f1"
      ]
    },
    "python": {
      "key": "python",
      "scope": "categories",
      "path": "/categories/python/",
      "pageKeys": [
        "v-0620935c",
        "v-43ee007e",
        "v-5d52d5ae"
      ]
    },
    "web": {
      "key": "web",
      "scope": "categories",
      "path": "/categories/web/",
      "pageKeys": [
        "v-e09dd050",
        "v-518e1fb8",
        "v-ca776e10",
        "v-08560cd0"
      ]
    }
  },
  "timeline": {}
}