/**
 * Generated by "@vuepress/plugin-blog"
 */

import sorters from './pageSorters'
import filters from './pageFilters'

export default [{
  pid: "tags",
  id: "esp32",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/esp32/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "opencv",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/opencv/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "python",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/python/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "vue",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/vue/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "pytroch",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/pytroch/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "esp32",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/esp32/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "python",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/python/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "web",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/web/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "pytroch",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/pytroch/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
}]